//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Economy.Editor.Authoring.AdminApi.Client.Http;


namespace Unity.Services.Economy.Editor.Authoring.AdminApi.Client.Models
{
    /// <summary>
    /// ConflictDeleteItemInUseErrorResponseData model
    /// </summary>
    [Preserve]
    [DataContract(Name = "conflict_delete_item_in_use_error_response_data")]
    internal class ConflictDeleteItemInUseErrorResponseData
    {
        /// <summary>
        /// Creates an instance of ConflictDeleteItemInUseErrorResponseData.
        /// </summary>
        /// <param name="references">List of references.</param>
        [Preserve]
        public ConflictDeleteItemInUseErrorResponseData(List<EntityItemBrief> references)
        {
            References = references;
        }

        /// <summary>
        /// List of references.
        /// </summary>
        [Preserve]
        [DataMember(Name = "references", IsRequired = true, EmitDefaultValue = true)]
        public List<EntityItemBrief> References{ get; }

        /// <summary>
        /// Formats a ConflictDeleteItemInUseErrorResponseData into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (References != null)
            {
                serializedModel += "references," + References.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a ConflictDeleteItemInUseErrorResponseData as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            return dictionary;
        }
    }
}
