//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Economy.Editor.Authoring.AdminApi.Client.Http;


namespace Unity.Services.Economy.Editor.Authoring.AdminApi.Client.Models
{
    /// <summary>
    /// EntityItemBrief model
    /// </summary>
    [Preserve]
    [DataContract(Name = "entity-item-brief")]
    internal class EntityItemBrief
    {
        /// <summary>
        /// Creates an instance of EntityItemBrief.
        /// </summary>
        /// <param name="id">ID of the item.</param>
        /// <param name="type">Type of the item.</param>
        [Preserve]
        public EntityItemBrief(string id, TypeOptions type)
        {
            Id = id;
            Type = type;
        }

        /// <summary>
        /// ID of the item.
        /// </summary>
        [Preserve]
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id{ get; }

        /// <summary>
        /// Type of the item.
        /// </summary>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeOptions Type{ get; }

        /// <summary>
        /// Type of the item.
        /// </summary>
        /// <value>Type of the item.</value>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeOptions
        {
            /// <summary>
            /// Enum VIRTUALPURCHASE for value: VIRTUAL_PURCHASE
            /// </summary>
            [EnumMember(Value = "VIRTUAL_PURCHASE")]
            VIRTUALPURCHASE = 1
        }

        /// <summary>
        /// Formats a EntityItemBrief into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Id != null)
            {
                serializedModel += "id," + Id + ",";
            }
            serializedModel += "type," + Type;
            return serializedModel;
        }

        /// <summary>
        /// Returns a EntityItemBrief as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Id != null)
            {
                var idStringValue = Id.ToString();
                dictionary.Add("id", idStringValue);
            }

            var typeStringValue = Type.ToString();
            dictionary.Add("type", typeStringValue);

            return dictionary;
        }
    }
}
