//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Economy.Editor.Authoring.AdminApi.Client.Http;


namespace Unity.Services.Economy.Editor.Authoring.AdminApi.Client.Models
{
    /// <summary>
    /// GetPublishedResourcesResponse model
    /// </summary>
    [Preserve]
    [DataContract(Name = "get_published_resources_response")]
    internal class GetPublishedResourcesResponse
    {
        /// <summary>
        /// Creates an instance of GetPublishedResourcesResponse.
        /// </summary>
        /// <param name="results">List of resources.</param>
        /// <param name="offset">Offset used by the request.</param>
        /// <param name="limit">Limit used by the request.</param>
        /// <param name="total">The total number of resources matched by the request.</param>
        [Preserve]
        public GetPublishedResourcesResponse(List<GetResourcesResponseResultsInner> results, int offset, int limit, int total)
        {
            Results = results;
            Offset = offset;
            Limit = limit;
            Total = total;
        }

        /// <summary>
        /// List of resources.
        /// </summary>
        [Preserve]
        [DataMember(Name = "results", IsRequired = true, EmitDefaultValue = true)]
        public List<GetResourcesResponseResultsInner> Results{ get; }

        /// <summary>
        /// Offset used by the request.
        /// </summary>
        [Preserve]
        [DataMember(Name = "offset", IsRequired = true, EmitDefaultValue = true)]
        public int Offset{ get; }

        /// <summary>
        /// Limit used by the request.
        /// </summary>
        [Preserve]
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public int Limit{ get; }

        /// <summary>
        /// The total number of resources matched by the request.
        /// </summary>
        [Preserve]
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public int Total{ get; }

        /// <summary>
        /// Formats a GetPublishedResourcesResponse into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Results != null)
            {
                serializedModel += "results," + Results.ToString() + ",";
            }
            serializedModel += "offset," + Offset.ToString() + ",";
            serializedModel += "limit," + Limit.ToString() + ",";
            serializedModel += "total," + Total.ToString();
            return serializedModel;
        }

        /// <summary>
        /// Returns a GetPublishedResourcesResponse as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            var offsetStringValue = Offset.ToString();
            dictionary.Add("offset", offsetStringValue);

            var limitStringValue = Limit.ToString();
            dictionary.Add("limit", limitStringValue);

            var totalStringValue = Total.ToString();
            dictionary.Add("total", totalStringValue);

            return dictionary;
        }
    }
}
