//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Economy.Editor.Authoring.AdminApi.Client.Http;


namespace Unity.Services.Economy.Editor.Authoring.AdminApi.Client.Models
{
    /// <summary>
    /// GetResourcesResponseResultsInner model
    /// </summary>
    [Preserve]
    [DataContract(Name = "get_resources_response_results_inner")]
    internal class GetResourcesResponseResultsInner
    {
        /// <summary>
        /// Creates an instance of GetResourcesResponseResultsInner.
        /// </summary>
        /// <param name="id">ID of the resource.</param>
        /// <param name="name">A descriptive name for the resource.</param>
        /// <param name="type">type param</param>
        /// <param name="initial">The initial amount of currency that a player is credited with upon first interaction. When &#x60;max&#x60; is used, &#x60;initial&#x60; must be less than &#x60;max&#x60;.</param>
        /// <param name="max">The maximum currency balance that a player can have. Calls that would result in the maximum being exceeded return an error.</param>
        /// <param name="customData">Max size when serialised 5 kilobits.</param>
        /// <param name="created">created param</param>
        /// <param name="modified">modified param</param>
        /// <param name="costs">The costs deducted from the player when making the purchase. A cost is an ID of a currency or inventory item, plus an amount. An item can be used in more than one cost line.</param>
        /// <param name="rewards">The rewards credited when making the purchase. A reward is an ID of a currency or inventory item, an amount and default instance data for inventory items. An item can be used in more than one reward line.</param>
        /// <param name="storeIdentifiers">storeIdentifiers param</param>
        [Preserve]
        public GetResourcesResponseResultsInner(string id, string name, TypeOptions type, long initial, long max, object customData, ModifiedMetadata created, ModifiedMetadata modified, List<VirtualPurchaseResourceResponseCostsInner> costs, List<VirtualPurchaseResourceResponseRewardsInner> rewards, RealMoneyPurchaseItemResponseStoreIdentifiers storeIdentifiers)
        {
            Id = id;
            Name = name;
            Type = type;
            Initial = initial;
            Max = max;
            CustomData = (IDeserializable) JsonObject.GetNewJsonObjectResponse(customData);
            Created = created;
            Modified = modified;
            Costs = costs;
            Rewards = rewards;
            StoreIdentifiers = storeIdentifiers;
        }

        /// <summary>
        /// ID of the resource.
        /// </summary>
        [Preserve]
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id{ get; }

        /// <summary>
        /// A descriptive name for the resource.
        /// </summary>
        [Preserve]
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name{ get; }

        /// <summary>
        /// Parameter type of GetResourcesResponseResultsInner
        /// </summary>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeOptions Type{ get; }

        /// <summary>
        /// The initial amount of currency that a player is credited with upon first interaction. When &#x60;max&#x60; is used, &#x60;initial&#x60; must be less than &#x60;max&#x60;.
        /// </summary>
        [Preserve]
        [DataMember(Name = "initial", IsRequired = false, EmitDefaultValue = true)]
        public long Initial{ get; }

        /// <summary>
        /// The maximum currency balance that a player can have. Calls that would result in the maximum being exceeded return an error.
        /// </summary>
        [Preserve]
        [DataMember(Name = "max", IsRequired = false, EmitDefaultValue = true)]
        public long Max{ get; }

        /// <summary>
        /// Max size when serialised 5 kilobits.
        /// </summary>
        [Preserve][JsonConverter(typeof(JsonObjectConverter))]
        [DataMember(Name = "customData", IsRequired = true, EmitDefaultValue = true)]
        public IDeserializable CustomData{ get; }

        /// <summary>
        /// Parameter created of GetResourcesResponseResultsInner
        /// </summary>
        [Preserve]
        [DataMember(Name = "created", IsRequired = true, EmitDefaultValue = true)]
        public ModifiedMetadata Created{ get; }

        /// <summary>
        /// Parameter modified of GetResourcesResponseResultsInner
        /// </summary>
        [Preserve]
        [DataMember(Name = "modified", IsRequired = true, EmitDefaultValue = true)]
        public ModifiedMetadata Modified{ get; }

        /// <summary>
        /// The costs deducted from the player when making the purchase. A cost is an ID of a currency or inventory item, plus an amount. An item can be used in more than one cost line.
        /// </summary>
        [Preserve]
        [DataMember(Name = "costs", IsRequired = false, EmitDefaultValue = true)]
        public List<VirtualPurchaseResourceResponseCostsInner> Costs{ get; }

        /// <summary>
        /// The rewards credited when making the purchase. A reward is an ID of a currency or inventory item, an amount and default instance data for inventory items. An item can be used in more than one reward line.
        /// </summary>
        [Preserve]
        [DataMember(Name = "rewards", IsRequired = false, EmitDefaultValue = true)]
        public List<VirtualPurchaseResourceResponseRewardsInner> Rewards{ get; }

        /// <summary>
        /// Parameter storeIdentifiers of GetResourcesResponseResultsInner
        /// </summary>
        [Preserve]
        [DataMember(Name = "storeIdentifiers", IsRequired = false, EmitDefaultValue = true)]
        public RealMoneyPurchaseItemResponseStoreIdentifiers StoreIdentifiers{ get; }

        /// <summary>
        /// Defines Type
        /// </summary>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeOptions
        {
            [EnumMember(Value = "MONEY_PURCHASE")]
            MONEYPURCHASE = 1,
            [EnumMember(Value = "INVENTORY_ITEM")]
            INVENTORYITEM = 2,
            [EnumMember(Value = "CURRENCY")]
            CURRENCY = 3,
            [EnumMember(Value = "VIRTUAL_PURCHASE")]
            VIRTUALPURCHASE = 4
        }

        /// <summary>
        /// Formats a GetResourcesResponseResultsInner into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Id != null)
            {
                serializedModel += "id," + Id + ",";
            }
            if (Name != null)
            {
                serializedModel += "name," + Name + ",";
            }
            serializedModel += "type," + Type + ",";
            serializedModel += "initial," + Initial.ToString() + ",";
            serializedModel += "max," + Max.ToString() + ",";
            if (CustomData != null)
            {
                serializedModel += "customData," + CustomData.ToString() + ",";
            }
            if (Created != null)
            {
                serializedModel += "created," + Created.ToString() + ",";
            }
            if (Modified != null)
            {
                serializedModel += "modified," + Modified.ToString() + ",";
            }
            if (Costs != null)
            {
                serializedModel += "costs," + Costs.ToString() + ",";
            }
            if (Rewards != null)
            {
                serializedModel += "rewards," + Rewards.ToString() + ",";
            }
            if (StoreIdentifiers != null)
            {
                serializedModel += "storeIdentifiers," + StoreIdentifiers.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a GetResourcesResponseResultsInner as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Id != null)
            {
                var idStringValue = Id.ToString();
                dictionary.Add("id", idStringValue);
            }

            if (Name != null)
            {
                var nameStringValue = Name.ToString();
                dictionary.Add("name", nameStringValue);
            }

            var typeStringValue = Type.ToString();
            dictionary.Add("type", typeStringValue);

            var initialStringValue = Initial.ToString();
            dictionary.Add("initial", initialStringValue);

            var maxStringValue = Max.ToString();
            dictionary.Add("max", maxStringValue);

            return dictionary;
        }
    }
}
