//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Economy.Editor.Authoring.AdminApi.Client.Http;


namespace Unity.Services.Economy.Editor.Authoring.AdminApi.Client.Models
{
    /// <summary>
    /// VirtualPurchaseItemRequestCostsInner model
    /// </summary>
    [Preserve]
    [DataContract(Name = "virtual_purchase_item_request_costs_inner")]
    internal class VirtualPurchaseItemRequestCostsInner
    {
        /// <summary>
        /// Creates an instance of VirtualPurchaseItemRequestCostsInner.
        /// </summary>
        /// <param name="itemId">The ID of the currency or inventory item used as a cost.</param>
        /// <param name="amount">The amount of the item that is deducted as part of the purchase.</param>
        [Preserve]
        public VirtualPurchaseItemRequestCostsInner(string itemId, long amount)
        {
            ItemId = itemId;
            Amount = amount;
        }

        /// <summary>
        /// The ID of the currency or inventory item used as a cost.
        /// </summary>
        [Preserve]
        [DataMember(Name = "itemId", IsRequired = true, EmitDefaultValue = true)]
        public string ItemId{ get; }

        /// <summary>
        /// The amount of the item that is deducted as part of the purchase.
        /// </summary>
        [Preserve]
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public long Amount{ get; }

        /// <summary>
        /// Formats a VirtualPurchaseItemRequestCostsInner into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (ItemId != null)
            {
                serializedModel += "itemId," + ItemId + ",";
            }
            serializedModel += "amount," + Amount.ToString();
            return serializedModel;
        }

        /// <summary>
        /// Returns a VirtualPurchaseItemRequestCostsInner as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (ItemId != null)
            {
                var itemIdStringValue = ItemId.ToString();
                dictionary.Add("itemId", itemIdStringValue);
            }

            var amountStringValue = Amount.ToString();
            dictionary.Add("amount", amountStringValue);

            return dictionary;
        }
    }
}
