//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.GameBackend.Economy.Http;



namespace Unity.GameBackend.Economy.Models
{
    /// <summary>
    /// InventoryDeleteRequest model
    /// <param name="writeLock">The write lock for the inventory instance.</param>
    /// </summary>

    [Preserve]
    [DataContract(Name = "inventory-delete-request")]
    public class InventoryDeleteRequest
    {
        /// <summary>
        /// Creates an instance of InventoryDeleteRequest.
        /// </summary>
        /// <param name="writeLock">The write lock for the inventory instance.</param>
        [Preserve]
        public InventoryDeleteRequest(string writeLock = default)
        {
            WriteLock = writeLock;
        }

        /// <summary>
        /// The write lock for the inventory instance.
        /// </summary>
        [Preserve]
        [DataMember(Name = "writeLock", EmitDefaultValue = false)]
        public string WriteLock{ get; }
    
    }
}

