//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.GameBackend.Economy.Http;



namespace Unity.GameBackend.Economy.Models
{
    /// <summary>
    /// InventoryRequestUpdate model
    /// <param name="instanceData">Instance data to be saved against the new inventory item. Max size when serialised 5kb.</param>
    /// <param name="writeLock">The write lock for the inventory instance.</param>
    /// </summary>

    [Preserve]
    [DataContract(Name = "inventory-request-update")]
    public class InventoryRequestUpdate
    {
        /// <summary>
        /// Creates an instance of InventoryRequestUpdate.
        /// </summary>
        /// <param name="instanceData">Instance data to be saved against the new inventory item. Max size when serialised 5kb.</param>
        /// <param name="writeLock">The write lock for the inventory instance.</param>
        [Preserve]
        public InventoryRequestUpdate(object instanceData, string writeLock = default)
        {
            InstanceData = new JsonObject(instanceData);
            WriteLock = writeLock;
        }

        /// <summary>
        /// Instance data to be saved against the new inventory item. Max size when serialised 5kb.
        /// </summary>
        [Preserve]
        [JsonConverter(typeof(JsonObjectConverter))]
        [DataMember(Name = "instanceData", IsRequired = true, EmitDefaultValue = true)]
        public JsonObject InstanceData{ get; }
        /// <summary>
        /// The write lock for the inventory instance.
        /// </summary>
        [Preserve]
        [DataMember(Name = "writeLock", EmitDefaultValue = false)]
        public string WriteLock{ get; }
    
    }
}

