//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.GameBackend.Economy.Http;



namespace Unity.GameBackend.Economy.Models
{
    /// <summary>
    /// PlayerInventoryResponse model
    /// <param name="results">List of Players Inventory Items.</param>
    /// <param name="links">links param</param>
    /// </summary>

    [Preserve]
    [DataContract(Name = "player_inventory_response")]
    public class PlayerInventoryResponse
    {
        /// <summary>
        /// Creates an instance of PlayerInventoryResponse.
        /// </summary>
        /// <param name="results">List of Players Inventory Items.</param>
        /// <param name="links">links param</param>
        [Preserve]
        public PlayerInventoryResponse(List<InventoryResponse> results, PlayerCurrencyBalanceResponseLinks links)
        {
            Results = results;
            Links = links;
        }

        /// <summary>
        /// List of Players Inventory Items.
        /// </summary>
        [Preserve]
        [DataMember(Name = "results", IsRequired = true, EmitDefaultValue = true)]
        public List<InventoryResponse> Results{ get; }
        /// <summary>
        /// 
        /// </summary>
        [Preserve]
        [DataMember(Name = "links", IsRequired = true, EmitDefaultValue = true)]
        public PlayerCurrencyBalanceResponseLinks Links{ get; }
    
    }
}

